### ISSUE TITLE
Wonka setup - user/password blocker?

### ISSUE THREAD

**Issue by tzdanows** [nycmkm/wonka#48]
Hi! I've been working on trying out Wonka but ran into issues when trying to set up username/passwords in the Rails console.

I would run:
`rails console`
and then run the following command with a different email/password of course:
`User.create!(email: henry@gmail.com, password: mypassword)`
and ran into the following bug:

![image](https://user-images.githubusercontent.com/30015060/232278907-14ff2864-c7b3-4e37-b88a-25170fffd4f8.png)

then later upon altering and running 
`User.create!(email: "henry@gmail.com", password: "mypassword")` 
I got the following error:
![image](https://user-images.githubusercontent.com/30015060/232279028-f7acbafa-5e00-4227-8b1a-7b52cf7bb157.png)

I've already gone through a fair amount of errors due to an old version of Ruby being on my PC without my knowledge. So I'll be stopping here for tonight but was wondering if someone with more knowledge of the project would be open to helping me troubleshoot. I think it's a database issue but I'm not entirely sure

if you wanted to contact on discord, I reply faster => PRIME#0001

**Comment by gdiggs** [comment]
Hey! As you figured out, the first problem you ran into was a Ruby syntax problem. Strings have to be wrapped in quotes to be literals.

How are you running the application? I need to make the Docker dependency clearer in the README - are you using the provided docker-compose file or trying to run the application natively?

**Comment by tzdanows** [comment]
I am running it locally as you perceived. I can give it a try with the docker-compose file and refer back. Thanks

**Comment by gdiggs** [comment]
Closing this because we got it working!
